
name: Release

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ main ]
    types: [ completed ]


jobs:

  version_update:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository == 'wwt/Jetflow' }}
    steps:
      - uses: actions/checkout@v2

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.build_changelog.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
